name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Обновлено до v4

      - name: Setup Python
        uses: actions/setup-python@v5 # Обновлено до v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --upgrade pip
          pip install Cython==0.29.33 buildozer

      - name: Build APK with Buildozer
        run: |
          # Создаем конфиг, если его нет
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          # Принимаем лицензии и настраиваем билд
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          # Запускаем сборку
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4 #ВОТ ТУТ БЫЛА ОШИБКА, ТЕПЕРЬ v4
        with:
          name: my-app-apk
          path: bin/*.apk
